diff --git a/third-party/PyPoE/PyPoE/cli/exporter/dat/handler.py b/third-party/PyPoE/PyPoE/cli/exporter/dat/handler.py
index 9de5cd7..f78a1df 100644
--- a/third-party/PyPoE/PyPoE/cli/exporter/dat/handler.py
+++ b/third-party/PyPoE/PyPoE/cli/exporter/dat/handler.py
@@ -30,6 +30,7 @@ See PyPoE/LICENSE
 # =============================================================================
 
 # Python
+import traceback
 
 # 3rd-party
 from tqdm import tqdm
@@ -41,6 +42,7 @@ from PyPoE.cli.core import console, Msg
 from PyPoE.cli.exporter import config
 from PyPoE.cli.exporter.util import get_content_path
 from PyPoE.poe.file.file_system import FileSystem
+from PyPoE.poe.file.specification.errors import SpecificationError
 
 # =============================================================================
 # Globals
@@ -111,7 +113,7 @@ class DatExportHandler:
         console(prefix + 'Loading file system...')
 
         file_system = FileSystem(root_path=path)
-        
+
         console(prefix + 'Reading .dat files')
 
         dat_files = {}
@@ -132,7 +134,12 @@ class DatExportHandler:
 
             df = dat.DatFile(name)
 
-            df.read(file_path_or_raw=data, use_dat_value=False)
+            try:
+                df.read(file_path_or_raw=data, use_dat_value=False)
+            except SpecificationError:
+                #traceback.print_exc()
+                print(traceback.format_exc())
+                remove.append(name)
 
             dat_files[name] = df
 
